#
# Global values
#
global:
  # EOS image tag:
  #   - Used by eos-server (qdb, mq, mgm, fst) (eos-all image)
  #             eos-instance-config (eos-all image)
  #             fusex in SWAN (eos-fusex image)
  tag: 4.8.57

  # SSS keytab:
  #   - Used by eos-server (qdb, mq, mgm, fst) and eos-instance-config
  #   - Anchor for fusex in SWAN
  sssKeytab:
    secret: &sssKeytabName sciencebox-eos-sss-keytab

#
# EOS
#
eos:
  mgm:
    mgmofs:
      instance: user
  fst:
    replicaCount: 4

#
# SWAN
#
swan:
  #
  # CVMFS mounts
  cvmfs:
    deployDaemonSet: &cvmfsDeployDS true
    deployCsiDriver: &cvmfsDeployCSI false
    useCsiDriver: &cvmfsUseCSI false
    repositories: &cvmfsRepos
      - cvmfs-config.cern.ch
      - sft.cern.ch
      - sft-nightlies.cern.ch

  #
  # EOS Fusex mount
  eos:
    deployDaemonSet: &eosDeployDS true
    deployCsiDriver: &eosDeployCSI false
    useCsiDriver: &eosUseCSI false
  fusex:
    # TODO
    # Crashes because uses pidof, that does not exist in container
    # Remove once fusex (likely 0.0.6) is fixed
    #probes:
    #  liveness: false
    fusex:
      keytab:
        secret: *sssKeytabName
      hostMountpoint: /var/eos
      config:
        oauth2: 1
        sss: 1
        # TODO: eos_mgm_alias should be guessed.
        #eos_mgm_alias: "eos-mgm.default.svc.cluster.local"
        eos_mgm_alias: "sciencebox-mgm.default.svc.cluster.local"

  #
  # JupyterHub
  jupyterhub:
    proxy:
      secretToken:
    hub:
      # The default (pvc) is not working in openstack...
      # TODO: Add some persistency here
      db:
        type: sqlite-memory
      extraEnv:
        JUPYTERHUB_CRYPT_KEY:
      cookieSecret:
      config:
        SwanKubeSpawner:
          local_home: False
        KeyCloakAuthenticator:
          oidc_issuer:
          client_id:
          # TODO retrieve from app portal
          client_secret:
          # TODO: We should infer pick the url automatically...
          oauth_callback_url:
          # With the CERN SSO we will get a valid token for EOS. If the eosxd supports oauth,
          # we will be able to use it from the terminal, even with local_home=True.
          # The oCIS idp probably doesn't support exchanging tokens, but we will be able to re-use
          # the swan token with EOS if needed (although we shouldn't)
          exchange_tokens:
            - eos-service
            - cernbox-service
        JupyterHub:
          # We should expose cernbox and swan from the same url to simplify the deployment
          # We can do that by using different base url's for each.
          # I hope this simplifies the ScienceBox ingress as well
          base_url: /swan
      extraConfig:
        # TODO change the config to use the oCIS idp
        # Might need fixes on the swan code cause we break if we don't set user_roles (at least when using GPU).
        00-authConf: |
          def pre_spawn_hook(authenticator, spawner, auth_state):
            spawner.environment['ACCESS_TOKEN'] = auth_state['exchanged_tokens']['eos-service']
            spawner.environment['OAUTH_INSPECTION_ENDPOINT'] = authenticator.userdata_url.replace('https://', '')
            spawner.user_uid = str(str(auth_state['oauth_user']['cern_uid'])) # k8s only supports values as strings!
            decoded_token = authenticator._decode_token(auth_state['access_token'])
            spawner.user_roles = authenticator.claim_roles_key(authenticator, decoded_token)
          c.KeyCloakAuthenticator.pre_spawn_hook = pre_spawn_hook
        02-spawnError: |
          cernbox_url = 'CHANGE_ME' # This should come from the ScienceBox config !! If necessary, this can come as an env var

          SPAWN_ERROR_MESSAGE = f"""SWAN could not start a session for your user, please try again. If the problem persists, please check:
          <ul>
              <li>Do you have a CERNBox account? If not, click <a href="{cernbox_url}" target="_blank">here</a>.</li>
              <li>Check with the service manager that SWAN is running properly.</li>
          </ul>"""
          c.SpawnHandlersConfigs.spawn_error_message = SPAWN_ERROR_MESSAGE
        03-simpleForm: |
          # Remove this to enable the full form
          c.SwanSpawner.options_form = open('/srv/jupyterhub/jupyterhub_form.html').read()
    singleuser:
      cpu:
        limit: .5
        guarantee: .5
      cvmfs:
        deployDaemonSet: *cvmfsDeployDS
        deployCsiDriver: *cvmfsDeployCSI
        useCsiDriver: *cvmfsUseCSI
        repositories: *cvmfsRepos
      eos:
        deployDaemonSet: *eosDeployDS
        deployCsiDriver: *eosDeployCSI
        useCsiDriver: *eosUseCSI
      extraEnv:
        # The sharing functionality won't work because we are deploying oCIS and not oc10
        # This will be replaced in the future with the CS3 APIs
        # SHARE_CBOX_API_DOMAIN: LOCAL_CBOX_URL__CHANGE_ME
        # SHARE_CBOX_API_BASE: /cernbox/swanapi/v1
        HELP_ENDPOINT: https://raw.githubusercontent.com/swan-cern/help/up2u/
        # FIXME Create a galery for ScienceBox? Or the normal one should redirect to different instances?
        # GALLERY_URL: https://swan-gallery.web.cern.ch/

    # TODO For some reason this is not working... We're still debugging
    prePuller:
      hook:
        enabled: false

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: true
        nginx.ingress.kubernetes.io/force-ssl-redirect: true
        #nginx.ingress.kubernetes.io/rewrite-target: /
        #nginx.ingress.kubernetes.io/secure-backends: "true"
      hosts:
        #- hostname_where_the_ingress_lives
      # tls:
      #   - secretName: swan-tls-cert
      #     hosts:
      #       - diogo-swan.cern.ch

  # To decide if we keep this or we manage the tls secret differently
  # If we keep it, maybe should change the name from swan.secrets.ingress to smth else
  # swan:
  #   secrets:
  #     ingress:
  #       cert:
  #       key:
